### PR TITLE
adding language regarding casual mentions of slavery

### PR DESCRIPTION
**Pull request by cjwilburn**
So I added a line about casual mentions of slavery. I'd be open to editing this to include outmoded references to primary-secondary hardware and software patterns.

### CODE REVIEW

**Comment by zkat** [comment]
@cjwilburn I'd be cool with that edit. Perhaps even phrased as "Please consider using or asking about alternate terminology when referring to such metaphors in technology."

**Review by zkat — APPROVED** [review]
Lgtm. I'll let others have a chance to give their 2c before merging tho. Thanks, Courtney 💚

**Comment by cjwilburn** [comment]
You're most certainly welcome. Happy to help.

**Review by varjmes — APPROVED** [review]

**Comment by varjmes** [comment]
Thanks Cj!

**Pull request merged**
