### PR TITLE
Set page title for pages with pageminimal layout. Fixes #19

### LINKED ISSUE #19: Title Tags Not Set
Title tags have not been explicitly set for the pages. Right now, site URLs display as the title.

### PR DESCRIPTION
**Pull request by karanjthakkar**

### CODE REVIEW

**Comment by varjmes** [comment]
This is a duplicate of #23 so who ever reviews this should review that one first before this one.

Regardless of whether it is merged or not, thanks so much for the work @karanjthakkar!

**Comment by karanjthakkar** [comment]
@Charlotteis I feel pretty stupid right now :| Since the PR wasn't referenced in the issue, I just coded this up. But @matsieftw implementation looks better to me. I'm gonna close this. Thanks for the quick comment 💯

**Comment by varjmes** [comment]
Well, there is absolutely no need to feel silly! 💃 
I'll add a note on to the issue that a PR already exists.

Thanks again!

**Comment by matsieftw** [comment]
Hey @karanjthakkar, I did not know you could keyword reference an issue when making a PR so I tried to add it later, but it was too late. I apologize for the confusion. My next PRs/issues will be better notated though. This was a learning moment for me. Thanks!

**Pull request closed without merging**
