### PR TITLE
pages: new postsignup page with more info

### LINKED ISSUE #28: request: Update post-signup page to remind people of important stuff
The page should have a quick short message about the signup, and link users to the signup process document. It should also link to both the CoC and Enforcement policies.

Aside from that, it would be great to have that page link people to the resource channel and identity channel list, and encourage users to /admin after they log in to get into identity spaces.

We can probably just create public links to both of the channel listings, because I don't think they leak any particularly sensitive information besides the existence of those spaces (and only some of the identity channels are on that list, those that it's ok for others to know about).

### PR DESCRIPTION
**Pull request by zkat**
This should fulfill a lot of the things I was hoping to get wheelie to do. This should fix #28 and https://github.com/WeAllJS/wheelie-slack-app/issues/1

### CODE REVIEW

**Comment by varjmes** [comment]
We can update this with your real cool `/list-private` `/join-private` commands wowowooww. Happy to do it but I don't want to step on your commits without permission.

**Comment by zkat** [comment]
@Charlotteis feel free to push to this branch!

**Comment by varjmes** [comment]
@zkat updated. Hope it helps.

**Comment by zkat** [comment]
This looks great, @Charlotteis! Thank you <3

**Comment by varjmes** [comment]
weeeee

**Pull request merged**
