### PR TITLE
adding point about misuse of content warnings

### PR DESCRIPTION
**Pull request by cjwilburn**
I think this, like the change in `weallbehave` could use a little clarity. Suggestions on language changes welcome.

### CODE REVIEW

**Review by AgentAntelope — APPROVED** [review]

**Comment by varjmes** [comment]
As I said in the other PR, not sure the second sentence is needed.

**Comment by cjwilburn** [comment]
@Charlotteis this one is ready to go, as well. Thanks for taking a look.

**Comment by varjmes** [comment]
Thanks @cjwilburn :D

**Review by varjmes — COMMENTED** [review]
nice

**Pull request merged**
